curve_tools: d3_np_fs(): fix gcc7 build
[ 15%] Building C object src/CMakeFiles/lib_darktable.dir/common/curve_tools.c.o
In function 'd3_np_fs.part.2',
    inlined from 'd3_np_fs':
/home/lebedevri/darktable/src/common/curve_tools.c:114:5: error: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
   x = (float *)calloc(n, sizeof(float));
   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/lebedevri/darktable/src/common/curve_tools.c:26:0:
/home/lebedevri/darktable/src/common/curve_tools.c: In function 'd3_np_fs':
/usr/include/stdlib.h:429:14: note: in a call to allocation function 'calloc' declared here
 extern void *calloc (size_t __nmemb, size_t __size)
              ^~~~~~

(cherry picked from commit 97e66ba84a2ce3c4d53027ebf7c81cc6302ff599)