common:dwt: Add missing include for __DT_CLONE_TARGETS__
In file included from src/common/dwt.c:19:
src/common/imagebuf.h:59:21: error: expected ';' before 'static'
   59 | __DT_CLONE_TARGETS__
      |                     ^
      |                     ;
   60 | static inline void dt_simd_memcpy(const float *const __restrict__ in,
      | ~~~~~~