Fix build with clang-21
Error Message:

darktable-5.2.0/data/kernels/soften.cl:33:18: error: use of undeclared identifier 'read_imagef'
   33 |   float4 pixel = read_imagef(in, sampleri, (int2)(x, y));
      |                  ^~~~~~~~~~~

https://github.com/llvm/llvm-project/commit/c1aebd495be0e468044f716a3a0ff98fccccb2be
wrapped all the image function declarations in the __IMAGE_SUPPORT__
macro, so darktable needs to define this macro in order to use these
functions.