amaze_demosaic_RT.cc: fix clang-3.8 build without SSE
[ 77%] Building CXX object src/iop/CMakeFiles/demosaic.dir/amaze_demosaic_RT.cc.o
/home/lebedevri/darktable/src/iop/amaze_demosaic_RT.cc:1176:54: error: absolute value function 'fabsf' given an argument of type 'double' but has parameter of type 'float' which may cause truncation of value [-Werror,-Wabsolute-value]
            if((0.5 - varwt) * (0.5 - diffwt) > 0 && fabsf(0.5 - diffwt) < fabsf(0.5 - varwt))
                                                     ^
Since those variables are float, i guess fabsf() was actually meant there.