Don't call __builtin_cpu_supports on OSX.
Add an exclusion condition to calling __builtin_cpu_supports for
OSX. clang-3.[78] from macports claims that
__has_builtin(__builtin_cpu_supports) is true and will compile; however,
when linking the darktable library, I see the following error:

  Undefined symbols for architecture x86_64:
    "___cpu_model", referenced from:
        _dt_init in darktable.c.o
  ld: symbol(s) not found for architecture x86_64

By excluding this and using the fallback, DT can then be built with
clang-mp-3.7 or clang-mp-3.8, and OpenMP will work for C and C++. As a
bonus, this method doesn't require modifications to
/opt/local/var/macports/macports.conf as per the building instructions
in packaging/macosx/BUILD.txt. If someone wants to test this and is
using macports, add this line to /opt/local/etc/macports/variants.conf:

  +ld64_xcode +openmp +no_gnome +no_x11 +quartz -x11 -gnome

Make the build directory and from the build directory type:

  CC=clang-mp-3.7 CXX=clang++-mp-3.7 cmake ..