Fix logic for enabling cloned functions
A fix went in to fix building with Musl but the logic was flawed.
Instead of only checking __GLIBC__ on Linux or Hurd it checks this
everywhere and __GLIBC__ has no relevance outside of Linux or Hurd.

Check for __OpenBSD__ which does not have ifunc support.

Check for PPC also __GLIBC__.

From FreeBSD/ppc64..

iop_profile.c:1273:6: error: 'target_clones' attribute needs GLIBC (2.23 and newer) that exports hardware capability bits