http server: SOUP_CHECK_VERSION was introduced in 2.42 Fixes build on some ancient systems (e.g. ubuntu 12.04)
With previous versions, compilation fails with the following message:
darktable/src/common/http_server.c:27:56: error: missing binary operator before token "("
#if !defined(SOUP_MAJOR_VERSION) || !SOUP_CHECK_VERSION(2, 48, 0)