dt_colorspaces_set_display_profile(): fix non-X11 build.
fixing compile errror:
error: '_gtk_get_monitor_num' defined but not used [-Werror=unused-function]

(cherry picked from commit fb1b18350adfa241025b554a07c969c66923cd3f)