Reflect rename of .desktop file in POTFILES.in
Recently the name of the desktop file changed from
darktable.desktop.in to org.darktable.darktable.desktop.in,
but even though the original commit (17508f1) did change
POTFILES.in, it seems that this change was accidentally reverted
afterwards, so intltool-update is confused:

$ intltool-update -pot
can't open ./../build/share/darktable/darktable.desktop.in: No such file or directory at /usr/bin/intltool-extract line 212.
xgettext: error while opening "../build/bin/conf_gen.h" for reading: No such file or directory
ERROR: xgettext failed to generate PO template file. Please consult
       error message above if there is any.

$ intltool-update pt_BR
can't open ./../build/share/darktable/darktable.desktop.in: No such file or directory at /usr/bin/intltool-extract line 212.
xgettext: error while opening "../build/share/darktable/darktable.desktop.in.h" for reading: No such file or directory
ERROR: xgettext failed to generate PO template file. Please consult
       error message above if there is any.

This patch changes the desktop file name in POTFILES.in so
intltool-update runs as expected.