http server: SOUP_CHECK_VERSION was introduced in 2.42 Fixes build on some ancient systems (e.g. ubuntu 12.04)
With previous versions, compilation fails with the following message:
darktable/src/common/http_server.c:27:56: error: missing binary operator before token "("

(cherry picked from commit 55f1b3ee7e30dbb1d311648c401f542adb703f29)