Do not trust __has_builtin(__builtin_cpu_supports) on FreeBSD
The default compiler (clang 3.7.0 as of this commit) tells it has
`__builtin_cpu_supports`, but the underlying FreeBSD library does not
have it. This leads to the following missing symbol:
    libdarktable.so: undefined reference to `__cpu_model'

Therefore, skip `__has_builtin(__builtin_cpu_supports)` on FreeBSD for
now.