Use a switch statement in dt_masks_create
`dt_masks_create` takes a dt_masks_type_t enum as input and returns a
dt_masks_form_t as output.  Before this commit, the mask type was tested
via cascading `if/else if` branches, this commit changes the tests to use a
switch/case statement.

The functionality should be the same, but the advantage of using the
switch/case statement is that if the dt_masks_type_t enum is ever
changed, the compiler will give us a warning.  For example, the
cascading `if/else if` didn't handle DT_MASKS_NONE/CLONE/NON_CLONE and
the compiler will emit a warning like this:

```
/Users/aaron/git/darktable/src/develop/masks/masks.c:843:11: fatal error: enumeration values 'DT_MASKS_NONE', 'DT_MASKS_CLONE', and 'DT_MASKS_NON_CLONE' not handled in switch [-Wswitch]
  843 |   switch (type)
      |           ^~~~
/Users/aaron/git/darktable/src/develop/masks/masks.c:843:11: note: add missing switch cases
  843 |   switch (type)
      |           ^
1 error generated.
```

As far as I can tell, those values shouldn't be passed to this factory
method, so we can use the opportunity to flag those branches as
`dt_unreachable_codepath()`.