Clahe iop: process(): fix gcc7 build.
[ 91%] Building C object src/iop/CMakeFiles/clahe.dir/introspection_clahe.c.o
In file included from /home/lebedevri/darktable/build-gcc7/src/iop/introspection_clahe.c:2:0:
/home/lebedevri/darktable/src/iop/clahe.c: In function 'process._omp_fn.1':
/home/lebedevri/darktable/src/iop/clahe.c:200:7: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
       for(int b = 0; b < hMin; b++)
       ^~~

(cherry picked from commit 7f8281c32ef1b950d650f7536671e8444fec495d)