Partially revert "Add const qualifiers"
It broke clang-3.7 build:
error: duplicate 'const' declaration specifier [-Werror,-Wduplicate-decl-specifier]

This partially reverts commit dc7962d74211d7c56d610c8e77039d8a30ae2ebf.