J2K: use g_strlcpy() instead of g_snprintf()
Fixes debian build:
<<PKGBUILDDIR>>/src/common/imageio_j2k.c:106:3: error: format not a string literal and no format arguments [-Werror=format-security]
   g_snprintf(parameters.infile, sizeof(parameters.infile), filename);
   ^
/<<PKGBUILDDIR>>/src/common/imageio_j2k.c: In function 'dt_imageio_j2k_read_profile':
/<<PKGBUILDDIR>>/src/common/imageio_j2k.c:329:3: error: format not a string literal and no format arguments [-Werror=format-security]
   g_snprintf(parameters.infile, sizeof(parameters.infile), filename);
   ^