dt_dev_pixelpipe_process_rec(): fix clang build.
In file included from darktable/src/develop/pixelpipe.c:22:
darktable/src/develop/pixelpipe_hb.c:744:24: error: address of array 'module->op' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
  if(module && module->op) strncpy(module_name, module->op, sizeof(module_name));
            ~~ ~~~~~~~~^~

Was broken in 7d41b03e8403e21d8e07f4a6297b9998bf1ec12f ce77e71f8b698230b76832071408a2e90284655b.

(cherry picked from commit c2a424b2790e8e3059c50f4a1f93640019649f2b)