colorbalance iop: fix clang build: N_(): expression result unused
[ 52%] Building C object src/iop/CMakeFiles/colorbalance.dir/introspection_colorbalance.c.o
In file included from /home/lebedevri/darktable/build/src/iop/introspection_colorbalance.c:21:
/home/lebedevri/darktable/src/iop/colorbalance.c:593:6: error: expression result unused [-Werror,-Wunused-value]
  N_("factor of lift");
     ^~~~~~~~~~~~~~~~

and so on