colorspaces: compilation fix, add missing header includes
when compiled on Debian/SID of the day with options:
--disable-gnome-keyring --disable-kwallet --disable-flickr --disable-unity

darktable/src/common/imageio.c:672:17: error: ‘DT_COLORSPACE_SRGB’ undeclared (first use in this function)
darktable/src/common/imageio.c:676:22: error: ‘DT_COLORSPACE_NONE’ undeclared (first use in this function)
darktable/src/common/imageio.c:685:15: error: unknown type name ‘dt_colorspaces_color_profile_type_t’
darktable/src/gui/gtk.c:611:5: error: implicit declaration of function ‘dt_colorspaces_set_display_profile’ [-Werror=implicit-function-declaration]
darktable/src/views/slideshow.c:352:56: error: ‘DT_COLORSPACE_DISPLAY’ undeclared (first use in this function)

(cherry picked from commit e97ed356fcbb5e7a46daab1bf8c1c6dfae3d6d14)