Clang: do not error-out on strange varargs warning
/home/lebedevri/darktable/src/control/signal.c:205:24: error: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Werror,-Wvarargs]
  va_start(extra_args, signal);
                       ^
/home/lebedevri/darktable/src/control/signal.c:182:77: note: parameter of type 'dt_signal_t' (aka 'enum dt_signal_t') is declared here
void dt_control_signal_raise(const dt_control_signal_t *ctlsig, dt_signal_t signal, ...)
                                                                            ^

(cherry picked from commit ae00c0fcd2865abb92bf329497ddb7749cc4ed16)