Move all trivial param cleanup cases into dt_control_job_dispose()
For that, make dt_control_job_get_params() return  const void* pointer,
because it can not be de-allocated without typecasting:
 error: passing argument 1 of ‘free’ discards ‘const’ qualifier from pointer target type