dt_mipmap_cache_init(): fix build with clang
i386, clang-3.8

[ 16%] Building C object src/CMakeFiles/lib_darktable.dir/common/mipmap_cache.c.o
/home/lebedevri/darktable/src/common/mipmap_cache.c:464:67: error: implicit conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned int') changes value from 8589934592 to 0 [-Werror,-Wconstant-conversion]
  size_t max_mem = CLAMPS(cache_memory, 100u << 20, ((uint64_t)8) << 30);
         ~~~~~~~                                    ~~~~~~~~~~~~~~^~~~~
/home/lebedevri/darktable/src/common/darktable.h:136:58: note: expanded from macro 'CLAMPS'

(cherry picked from commit 0800e4d3735d8b990bebc8e9ea4b34ed47098d30)