dt_ellipse_events_mouse_moved(): fix gcc7 false-positive [-Wmaybe-uninitialized]
[ 16%] Building C object src/CMakeFiles/lib_darktable.dir/develop/masks/masks.c.o
In file included from /home/lebedevri/darktable/src/develop/masks/masks.c:34:0:
/home/lebedevri/darktable/src/develop/masks/ellipse.c: In function 'dt_ellipse_events_mouse_moved.isra.44.part.45':
/home/lebedevri/darktable/src/develop/masks/ellipse.c:689:7: error: 'ins' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     if(ins)
       ^

(cherry picked from commit 8827726a50d9e5a9a6504206c4ada18034350b43)