Remove unused functions for dt/dttags writing
From: Bruce Guenter <bruce@untroubled.org>
To: darktable-devel@lists.sourceforge.net
Date: Tue, 11 Jan 2011 09:55:38 -0600

The commit "Trivial fixes of clang warnings." (c895dcc) introduced
several fatal compilation errors in dt_imageio_dt_write:

[ 39%] Building C object
src/CMakeFiles/lib_darktable.dir/common/imageio.c.o
cc1: warnings being treated as errors
src/common/imageio.c: In function 'dt_imageio_dt_write':
src/common/imageio.c:882: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result
src/common/imageio.c:886: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result
src/common/imageio.c:888: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result
src/common/imageio.c:889: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result
src/common/imageio.c:891: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result
src/common/imageio.c:892: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result

This function is not referenced anywhere in the darktable sources, so
remove it.